apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: couch
data:
  DB_HOST: mydb
  DB_PORT: "5432"
  DB_NAME: myuser
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: couch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi-image
          image: docker.io/francisjohn61981/fastapi-image:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: fastapi-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: fastapi-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: fastapi-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: couchdb-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: couchdb-secret
                  key: DB_PASS
          readinessProbe:
            tcpSocket: 
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: couch
spec:
  selector:
    app: fastapi
  ports:
    - port: 8000
      targetPort: 8000